---
#
# bosh -e vbox -d gobonniego deploy example.yml
#
name: gobonniego

instance_groups:
- name: vm_to_benchmark
  azs: [z1]
  lifecycle: errand
  instances: 1
  jobs:
  - name: gobonniego
    release: gobonniego
    properties:
      args: -v -size 0.5 -iops-duration 1.0
      dir: /var/vcap/data
  vm_type: default
  stemcell: default
  networks:
  - name: default

releases:
- name: gobonniego
  version: latest

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

update:
  canaries: 2
  max_in_flight: 1
  canary_watch_time: 5000-60000
  update_watch_time: 5000-60000
